### ISSUE TITLE
Gekko config failure

### ISSUE THREAD

**Issue by Gab0** [DustinJSilk/reactive-trader#1]
I follow the procedure on readme, but when it comes to `npm run trade`:

```
/home/gabs/Gekko/core/exchangeChecker.js:65
  var slug = conf.exchange.toLowerCase();
                  ^

TypeError: Cannot read property 'exchange' of undefined
```

It seems gekko is not loading config properly, idk

**Comment by DustinJSilk** [comment]
Ive just pushed up a quick fix if you could give that a go and let me know.
I updated the sample-config.js.

**Comment by Gab0** [comment]
Nice, it works now ^^
