### ISSUE TITLE
npm run trade does not appear to work

### ISSUE THREAD

**Issue by xteejx** [DustinJSilk/reactive-trader#3]
Running this doesn't seem to work at all.
Developer: what version of nodejs and npm are you using when this is workin as whatever combination I try, it doesn't seem to want to work at all. I either get promise errors, or path errors (../../config).

Great project though, had a similar idea myself (and implement it manually daily), so this would be perfect if it can get up and running.

Have made developers on gekko's discord channel aware of the project too :)

**Comment by xteejx** [comment]
Upgrading nodejs and npm to the latest stable versions solved all issues. It is worth noting that the gekko config must be called config.js or this doesn't work. Next README update maybe? :) 
Awesome stuff!

**Comment by DustinJSilk** [comment]
Glad to hear you got it up and running. Ill give it some more time today. And will update the readme too ;)

**Comment by xteejx** [comment]
Brilliant! Thanks man.
